[package]
name = "packetry-db"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"

[dependencies]
anyhow     = "1"
arc-swap   = "1.6"
bytemuck   = "1"
humansize = "2.1.3"
itertools  = "0.15"
lrumap     = "0.1"
memmap2    = "0.9"
num-format = "0.4"
page_size  = "0.6"
tempfile   = "3"

[dev-dependencies]
bytemuck_derive = "1.5"
rand            = "0.10"
rand_xorshift   = "0.5"
